export interface ImageDimensions {
  width: number;
  height: number;
}

// Public-folder images do not expose Astro's imported ImageMetadata, so keep
// their intrinsic dimensions here for the Image component and stable layout.
const imageDimensions: Record<string, ImageDimensions> = {
  "/assets/card-tests/collibris/aube-musique.webp": { width: 1771, height: 2480 },
  "/assets/card-tests/collibris/aube-premiere-couverture.webp": { width: 1997, height: 2906 },
  "/assets/card-tests/collibris/coeur-de-renard-mockup-2.webp": { width: 745, height: 1040 },
  "/assets/card-tests/collibris/phenix-003.webp": { width: 781, height: 1008 },
  "/assets/card-tests/collibris/pumpkin-space.webp": { width: 1640, height: 2360 },
  "/assets/card-tests/pokebox-sv3-5-199/front.webp": { width: 1466, height: 2048 },
  "/assets/covers/cdr-cover-broche.webp": { width: 1500, height: 1150 },
  "/assets/covers/coeur-de-renard-tome-2--broche.webp": { width: 1500, height: 1150 },
  "/assets/covers/coeur-de-renard-tome-2--relie.webp": { width: 829, height: 1226 },
  "/assets/covers/Cover_CDR_Ulule.webp": { width: 778, height: 1199 },
  "/assets/covers/Cover_TLL.webp": { width: 1500, height: 1383 },
  "/assets/covers/Cover_TLL_broche.webp": { width: 1500, height: 1150 },
  "/assets/covers/fous-papillons-cover.webp": { width: 1500, height: 1150 },
  "/assets/covers/fous-papillons-featured.webp": { width: 1989, height: 2227 },
  "/assets/covers/le-coeur-dankaa-cover.webp": { width: 1500, height: 1383 },
  "/assets/gallery/brille-papillons--agape.webp": { width: 4116, height: 5202 },
  "/assets/gallery/brille-papillons--cover.webp": { width: 2500, height: 3800 },
  "/assets/gallery/coeur-de-renard--fortune-cigarette.webp": { width: 3000, height: 4000 },
  "/assets/gallery/coeur-de-renard--fortune-renard-2.webp": { width: 2442, height: 3364 },
  "/assets/gallery/coeur-de-renard--fortune.webp": { width: 1640, height: 2360 },
  "/assets/gallery/coeur-de-renard--marque-page.webp": { width: 1000, height: 2000 },
  "/assets/gallery/coeur-de-renard--planche-bd.webp": { width: 4677, height: 6614 },
  "/assets/gallery/coeur-de-renard--renard-fortune.webp": { width: 1952, height: 742 },
  "/assets/gallery/coeur-de-renard--renard-monstre.webp": { width: 3000, height: 4000 },
  "/assets/gallery/coeur-de-renard--renard.webp": { width: 1640, height: 2360 },
  "/assets/gallery/fous-papillons--chiara.webp": { width: 1399, height: 1600 },
  "/assets/gallery/fous-papillons--esther.webp": { width: 1131, height: 1600 },
  "/assets/gallery/fous-papillons--ethan.webp": { width: 1131, height: 1600 },
  "/assets/gallery/fous-papillons--frantz.webp": { width: 1131, height: 1600 },
  "/assets/gallery/les-douze-divins--aspen-chloe.webp": { width: 684, height: 701 },
  "/assets/gallery/les-douze-divins--aspen-dessin.webp": { width: 692, height: 691 },
  "/assets/gallery/les-douze-divins--aspen-sarah.webp": { width: 2048, height: 2048 },
  "/assets/gallery/notre-sang-dans-lhumus-de-la-foret--geina.webp": { width: 4000, height: 5000 },
  "/assets/gallery/notre-sang-dans-lhumus-de-la-foret--scene.webp": { width: 1273, height: 1563 },
  "/assets/gallery/trouver-la-lune--carte.webp": { width: 3543, height: 2953 },
  "/assets/gallery/trouver-la-lune--enfants.webp": { width: 3000, height: 4000 },
  "/assets/gallery/trouver-la-lune--jaquette.webp": { width: 6260, height: 2598 },
  "/assets/gallery/trouver-la-lune--locke-valor.webp": { width: 4000, height: 3808 },
  "/assets/gallery/trouver-la-lune--locke.webp": { width: 4000, height: 5000 },
  "/assets/gallery/trouver-la-lune--portrait-lune.webp": { width: 3000, height: 3639 },
  "/assets/gallery/trouver-la-lune--portrait-neige.webp": { width: 3000, height: 4000 },
  "/assets/gallery/trouver-la-lune--shadar.webp": { width: 2549, height: 3489 },
  "/assets/gallery/trouver-la-lune--valor.webp": { width: 3062, height: 4000 },
  "/assets/gallery/trouver-la-lune--valoretlocke.webp": { width: 2993, height: 3744 },
  "/assets/services/couvertures/cover-1.webp": { width: 1816, height: 1217 },
  "/assets/services/couvertures/cover-2.webp": { width: 2360, height: 1657 },
  "/assets/services/couvertures/cover-3.webp": { width: 2360, height: 1622 },
  "/assets/services/couvertures/cover-5.webp": { width: 2360, height: 1663 },
  "/assets/services/headers/header-eight.webp": { width: 1800, height: 2700 },
  "/assets/services/headers/header-eleven.webp": { width: 1800, height: 2700 },
  "/assets/services/headers/header-fifteen.webp": { width: 1800, height: 2700 },
  "/assets/services/headers/header-fourteen.webp": { width: 1800, height: 2700 },
  "/assets/services/headers/header-nine.webp": { width: 1800, height: 2700 },
  "/assets/services/headers/header-seven.webp": { width: 1800, height: 2700 },
  "/assets/services/headers/header-ten.webp": { width: 1800, height: 2700 },
  "/assets/services/headers/header-thirteen.webp": { width: 1800, height: 2700 },
  "/assets/services/headers/header-twelve.webp": { width: 1800, height: 2700 },
  "/assets/services/illustrations/illustration-eight.webp": { width: 1640, height: 2360 },
  "/assets/services/illustrations/illustration-eighteen.webp": { width: 1273, height: 1563 },
  "/assets/services/illustrations/illustration-eleven.webp": { width: 4000, height: 5000 },
  "/assets/services/illustrations/illustration-fifteen.webp": { width: 3506, height: 4001 },
  "/assets/services/illustrations/illustration-five.webp": { width: 4000, height: 4500 },
  "/assets/services/illustrations/illustration-fourteen.webp": { width: 1000, height: 1000 },
  "/assets/services/illustrations/illustration-nine.webp": { width: 1640, height: 2360 },
  "/assets/services/illustrations/illustration-seven.webp": { width: 1640, height: 2360 },
  "/assets/services/illustrations/illustration-seventeen.webp": { width: 3000, height: 4000 },
  "/assets/services/illustrations/illustration-six.webp": { width: 1640, height: 2360 },
  "/assets/services/illustrations/illustration-sixteen.webp": { width: 3000, height: 3000 },
  "/assets/services/illustrations/illustration-ten.webp": { width: 1640, height: 2360 },
  "/assets/services/illustrations/illustration-thirteen.webp": { width: 4000, height: 4500 },
  "/assets/services/illustrations/illustration-twelve.webp": { width: 4000, height: 5000 },
  "/assets/services/jaspages/jaspage-eight.webp": { width: 472, height: 1772 },
  "/assets/services/jaspages/jaspage-five.webp": { width: 319, height: 1819 },
  "/assets/services/jaspages/jaspage-four.webp": { width: 319, height: 2551 },
  "/assets/services/jaspages/jaspage-nine.webp": { width: 378, height: 2480 },
  "/assets/services/jaspages/jaspage-seven.webp": { width: 449, height: 2551 },
  "/assets/services/jaspages/jaspage-six.webp": { width: 319, height: 1819 },
  "/assets/services/maps/maps-height.webp": { width: 3543, height: 2953 },
  "/assets/services/maps/maps-one.webp": { width: 2048, height: 2048 },
  "/assets/services/maps/maps-seven.webp": { width: 1714, height: 2480 },
  "/assets/services/maps/maps-six.webp": { width: 2374, height: 2000 },
  "/assets/services/maps/maps-three.webp": { width: 3307, height: 2480 },
  "/assets/services/maps/maps-two.webp": { width: 780, height: 1196 },
  "/assets/services/pagedegarde/pdg2.webp": { width: 3223, height: 2360 },
  "/assets/services/pagedegarde/pdg3.webp": { width: 3041, height: 1563 },
  "/assets/services/pagedegarde/pdg4.webp": { width: 2360, height: 1696 },
  "/assets/services/pagedegarde/pdg5.webp": { width: 2360, height: 1696 },
  "/assets/services/premades/premade.webp": { width: 2360, height: 1657 },
  "/assets/services/premades/premade2.webp": { width: 2360, height: 1663 },
};

export const getImageDimensions = (src: string): ImageDimensions =>
  imageDimensions[src] ?? { width: 1600, height: 1600 };
