/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Links = {
  purchase?: Array<
    {
      _key: string;
    } & ExternalLink
  >;
};

export type Narrative = {
  hook?: string;
  description?: string;
};

export type BookReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "book";
};

export type Citation = {
  _id: string;
  _type: "citation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quoteNumber?: number;
  createdAt?: string;
  quote?: string;
  authorOfQuote?: string;
  book?: BookReference;
  bookTitle?: string;
  order?: number;
  published?: boolean;
};

export type Review = {
  _id: string;
  _type: "review";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  rating?: number;
  text?: string;
  excerpt?: string;
  book?: BookReference;
  bookLabel?: string;
  bookSlug?: string;
  date?: string;
  author?: string;
  source?: string;
  tag?: string;
  accent?: string;
  link?: string;
  isbn?: string;
  order?: number;
  published?: boolean;
};

export type GalleryItem = {
  _id: string;
  _type: "galleryItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  image?: MediaImage;
  book?: BookReference;
  bookSlug?: string;
  artist?: string;
  date?: string;
  description?: string;
  order?: number;
  published?: boolean;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type MediaImage = {
  _type: "mediaImage";
  image?: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
  label?: string;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  eyebrow?: string;
  price?: string;
  accent?: string;
  format?: string;
  universe?: string;
  focus?: string;
  gallery?: Array<
    {
      _key: string;
    } & ServiceGalleryItem
  >;
  tags?: Array<string>;
  description?: string;
  order?: number;
  published?: boolean;
};

export type ServiceGalleryItem = {
  _type: "serviceGalleryItem";
  image?: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
  label?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Book = {
  _id: string;
  _type: "book";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  identity?: {
    title?: string;
    subtitle?: string;
    tome?: string;
    saga?: string;
    series?: string;
    genres?: Array<string>;
    accent?: string;
  };
  publishing?: {
    status?: string;
    releaseDate?: string;
    defaultFormat?: string;
    defaultPrice?: string;
    defaultIsbn?: string;
    pages?: number;
    priceOptions?: Array<
      {
        _key: string;
      } & PriceOption
    >;
  };
  narrative?: {
    hook?: string;
    shortDescription?: string;
    longDescription?: string;
    quote?: string;
    details?: Array<
      {
        _key: string;
      } & BookDetail
    >;
  };
  media?: {
    cover?: MediaImage;
    editions?: Array<
      {
        _key: string;
      } & BookEdition
    >;
    relatedGalleryIds?: Array<string>;
  };
  links?: {
    purchase?: Array<
      {
        _key: string;
      } & ExternalLink
    >;
    playlists?: Array<
      {
        _key: string;
      } & ExternalLink
    >;
    chapterOneHref?: string;
  };
  marketing?: {
    isLatest?: boolean;
    featured?: {
      label?: string;
      kicker?: string;
      shortPitch?: string;
      media?: BookFeaturedMedia;
      stats?: Array<{
        label?: string;
        value?: string;
        _key: string;
      }>;
      spotlight?: Array<{
        label?: string;
        value?: string;
        _key: string;
      }>;
    };
  };
  order?: number;
  published?: boolean;
};

export type BookFeaturedMedia = {
  _type: "bookFeaturedMedia";
  type?: "image" | "video";
  image?: MediaImage;
  src?: string;
  poster?: MediaImage;
  gallery?: Array<
    {
      _key: string;
    } & MediaImage
  >;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type BookEdition = {
  _type: "bookEdition";
  id?: string;
  label?: string;
  media?: MediaImage;
  publishing?: EditionPublishing;
  links?: Links;
  narrative?: Narrative;
};

export type EditionPublishing = {
  _type: "editionPublishing";
  format?: string;
  price?: string;
  isbn?: string;
  pages?: number;
  releaseDate?: string;
  status?: string;
};

export type PriceOption = {
  _type: "priceOption";
  label?: string;
  value?: string;
};

export type BookDetail = {
  _type: "bookDetail";
  label?: string;
  value?: string;
};

export type ExternalLink = {
  _type: "externalLink";
  label?: string;
  href?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Links
  | Narrative
  | BookReference
  | Citation
  | Review
  | GalleryItem
  | SanityImageAssetReference
  | MediaImage
  | Service
  | ServiceGalleryItem
  | SanityImageCrop
  | SanityImageHotspot
  | Book
  | BookFeaturedMedia
  | Slug
  | BookEdition
  | EditionPublishing
  | PriceOption
  | BookDetail
  | ExternalLink
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
